name: Generate Webpage

on: 
  #push
  #pull_request:
  #  branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  #on:
  #push:
  #  branches: ['master']
  #  paths: 'build/*.json'
  workflow_dispatch:
jobs:
  update-proposal-webpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repo as target repo
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
 
      - name: Update pip and install sphinx and required tools
        run: |
          echo $GITHUB_WORKSPACE
          pip install --upgrade pip
          pip install lxml Sphinx sphinx_comments pyRestTable six
        
      - name: Pull the state of the source repo, i.e. the one with the rst source code
        run: |
          mkdir -p $GITHUB_WORKSPACE/source
          cd $GITHUB_WORKSPACE/source
          # ls $PWD
          git clone https://github.com/FAIRmat-Experimental/nexus_definitions.git
          cd $GITHUB_WORKSPACE/source/nexus_definitions
          git checkout fairmat
          # git status
          # ls $PWD
          # local repository is the target repo
          # mkdir -p docs
          make all
          # get commit id of the source repo, not of the nexus-fairmat-proposal target repo !
          MYCOMMITID=$(git log -1 | grep ^commit | cut -d " " -f 2)
          MYCOMMITTC=$(git log -1 | grep ^Date)
          # replace the links with the current one
          grep -rl '  https:\/\/github.com\/nexusformat\/definitions\/blob\/main' --exclude-dir=.git | xargs sed -i 's/  https:\/\/github.com\/nexusformat\/definitions\/blob\/main/  https:\/\/github.com\/FAIRmat-Experimental\/nexus_definitions\/tree\/fairmat/'
          cd $GITHUB_WORKSPACE          
          # git rev-parse @~)
          echo $MYCOMMITID
          # create sub-directory named $MYCOMMITID
          mkdir -p $GITHUB_WORKSPACE/$MYCOMMITID
          # ls
          # shopt -s extglob
          # mv !($MYCOMMITID) $MYCOMMITID
          mv $GITHUB_WORKSPACE/source/nexus_definitions/manual/build/html/* $GITHUB_WORKSPACE/$MYCOMMITID
          # ls $MYCOMMITID/*
          # replace time and commitid on main page
          cp $GITHUB_WORKSPACE/source/nexus_definitions/manual/source/sed/entry-page.html $GITHUB_WORKSPACE/index.html
          head -1000 $GITHUB_WORKSPACE/index.html
          sed -i 's/<<AUTO_INJECT_CURRENT_VERSION>>/https:\/\/FAIRmat-Experimental.github.io\/nexus-fairmat-proposal/'"$MYCOMMITID"'/index.html/' $GITHUB_WORKSPACE/index.html
          head -1000 $GITHUB_WORKSPACE/index.html
          echo "Resetting auto placeholders"
          echo $MYCOMMITTC
          echo $MYCOMMITID
          head -1000 $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          # sed -i 's/<<AUTO_INJECT_COMMIT_TC>>/\'$MYCOMMITTC\'/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          # sed -i 's/<<AUTO_INJECT_COMMIT_ID>>/'$MYCOMMITID'/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          # sed -i "s/<<AUTO_INJECT_COMMIT_ID>>/$MYCOMMITID/" $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          # sed -i 's/<<AUTO_INJECT_COMMIT_ID>>/'"$MYCOMMITID"'/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          # sed -i 's/&lt;&lt;AUTO_INJECT_COMMIT_ID&gt;&gt;/$MYCOMMITID/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          sed -i 's/&lt;&lt;AUTO_INJECT_COMMIT_TC&gt;&gt;/'"$MYCOMMITTC"'/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html 
          sed -i 's/&lt;&lt;AUTO_INJECT_COMMIT_ID&gt;&gt;/'"$MYCOMMITID"'/' $GITHUB_WORKSPACE/$MYCOMMITID/index.html          
          echo "Was auto inject commit id ??? replaced ???"
          head -1000 $GITHUB_WORKSPACE/$MYCOMMITID/index.html
          echo "Inspecting github workspace..."
          ls $GITHUB_WORKSPACE/*
          ls $GITHUB_WORKSPACE/$MYCOMMITID/*
          # echo "Inspect correct links in nxdls for nexus_definitions"
          # tail -1000 $MYCOMMITID/manual/build/html/classes/applications/NXapm.html
          # replace link in the index.html to the one under mycommitid/index.html
          # replace 
          #/home/runner/work/nexus-fairmat-proposal/nexus-fairmat-proposal/source/definitions/manual
          # create a repository with the commit id version 
          ## echo "Carrying changes over to local version of the repo for the specific commit !"
          ## cp -R $GITHUB_WORKSPACE/source/definitions/manual/build/html/* $GITHUB_WORKSPACE
          ## rm -rf $GITHUB_WORKSPACE/source
          ## ls $GITHUB_WORKSPACE
          ## #need to add a .nojekyll file into the root directory where the gh-pages will be served from
          ## #to enforce that gitpages uses the css of the page and not just show it with any css
          touch $GITHUB_WORKSPACE/.nojekyll

      - name: Commit files into the local repository from which this action was triggered
        run: |
          git config --local user.name "mkuehbach"
          git add .
          git commit -m "Updating the repository GitHub html pages in the docs folder"
  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true

